name: Build packages

on:
  workflow_call:
    secrets:
      gpgkey:
        required: true

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  changed-files:
    name: Assemble builds
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      modified_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get changed specs
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files: |
            **/*.spec

  xorg-x11-drv-nvidia:
    if: ${{ ! failure() && ! cancelled() && contains(needs.changed-files.outputs.modified_files, '/xorg-x11-drv-nvidia.spec') }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
    with:
      spec: xorg-x11-drv-nvidia/xorg-x11-drv-nvidia.spec
      deps: ${{ toJson(needs) }}

  nvidia-kmod:
    if: ${{ ! failure() && ! cancelled() && contains(needs.changed-files.outputs.modified_files, '/nvidia-kmod.spec') }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
      - xorg-x11-drv-nvidia
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
    with:
      spec: nvidia-kmod/nvidia-kmod.spec
      deps: ${{ toJson(needs) }}

  nvidia-modprobe:
    if: ${{ ! failure() && ! cancelled() && contains(needs.changed-files.outputs.modified_files, '/nvidia-modprobe.spec') }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
    with:
      spec: nvidia-modprobe/nvidia-modprobe.spec
      deps: ${{ toJson(needs) }}

  nvidia-persistenced:
    if: ${{ ! failure() && ! cancelled() && contains(needs.changed-files.outputs.modified_files, '/nvidia-persistenced.spec') }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
    with:
      spec: nvidia-persistenced/nvidia-persistenced.spec
      deps: ${{ toJson(needs) }}

  nvidia-settings:
    if: ${{ ! failure() && ! cancelled() && contains(needs.changed-files.outputs.modified_files, '/nvidia-settings.spec') }}
    uses: ./.github/workflows/reusable-build-rpm.yml
    needs:
      - changed-files
    secrets:
      gpgkey: ${{ secrets.gpgkey }}
    with:
      spec: nvidia-settings/nvidia-settings.spec
      deps: ${{ toJson(needs) }}
